# Generated by Django 4.1.13 on 2024-06-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=1000)),
                ('party_of_speech', models.CharField(max_length=1000)),
                ('description', models.TextField()),
            ],
        ),
    ]
